### ISSUE TITLE
Tuna effects automation

### ISSUE THREAD

**Issue by anmahade** [Dinahmoe/tuna#11]
Hi,
Great bunch of effects! I'm having a lot of fun playing around with them. However, I am having trouble figuring out how to automate parameters of a particular effect. For example if I have a chorus effect like so -
//////////////////////////////////////////////////////////////////////////////////////////
var chorus = new tuna.Chorus({
                 rate: 1.5,         //0.01 to 8+
                 feedback: 0.2,     //0 to 1+
                 delay: 0.0045,     //0 to 1
                 bypass: 0          //the value 1 starts the effect as bypassed, 0 or 1
             });

soundSource.buffer = buffer;
soundSource.connect(chorus.input);
chorus.connect(context.destination);

chorus.automate("feedback", 0.8,10,5); 
//////////////////////////////////////////////////////////////////////////////////////////
Could someone tell me whats the right way to go about automation of the feedback parameter as this does not seem to work.

Thanks,
Anand

**Comment by Theodeus** [comment]
Hey Anand!

I'm sure you've moved on (let's hope so :), but I'll answer this now for future reference. The automate function works on AudioParam's, by leveraging the built in automation functions in the Web Audio API. This means that some parameters won't be possible to automate as they're not AudioParams. To easily see which params are automatable, you can check the source of each Tuna effect and look at the defaults object. There you can see all parameters of the effect and whether they're automatable or not. 

Looking at the Chorus, I see that none of the params are automatable, so it might be an idea to look at adding custom automatisation for non-AudioParam parameters.
