### ISSUE TITLE
BiquadFilterNode typing issues (Chrome)

### ISSUE THREAD

**Issue by AnthonyDry** [Dinahmoe/tuna#14]
This isn't a huge problem but since enums on .FilterNode.type has changed and no longer supports just a number like before. We have to use the full name of the type of filter we want to use.
Like this: filterType: 'lowshelf', etc.
I looked thru the code and was thinking about adding a fix but I realised the fix would probably slow down  tuna since it was based on a switch case. Anyway maybe a change in the readme.md is enough for new users.
Ha det så bra!

**Comment by Theodeus** [comment]
Tack, och du med! ;)
